#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --error=CARRA2_DYN.log
#SBATCH --output=CARRA2_DYN.log
#SBATCH --job-name=CARRA2_DYN_EXTRACT
#SBATCH --ntasks=1
#SBATCH --mem=80GB
#SBATCH --qos=nf
#SBATCH --time=12:00:00

module load conda
conda activate ddenv_v2

DDIR=/scratch/swe4281/DDPM_DATA/CARR2DYN/DATA
SCRDIR=${PWD}
cd $DDIR || { echo "cd to $DDIR" ; exit ; }
python3 ${SCRDIR}/grib2nc_SURF.py ${DDIR} ./
exit 0
